services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpress_volume:${WP_FOLDER}
    networks:
      - inception
    depends_on:
      - wordpress
      - mariadb
    # restart: always

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_volume:${WP_FOLDER}
    networks:
      - inception
    depends_on:
      - mariadb
    environment:
      WP_FOLDER: ${WP_FOLDER}
      WP_LINUX_USER: ${WP_LINUX_USER}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_HOST: ${WP_DB_HOST}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_USER_PASSWORD: ${WP_DB_USER_PASSWORD}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      SECOND_WP_USER: ${SECOND_WP_USER}
      SECOND_WP_USER_EMAIL: ${SECOND_WP_USER_EMAIL}
      SECOND_WP_USER_PASSWORD: ${SECOND_WP_USER_PASSWORD}
  #   restart: always

  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_volume:${MARIADB_FOLDER}
    networks:
      - inception
    environment:
      MARIADB_LINUX_USER: ${MARIADB_LINUX_USER}
      MARIADB_ROOT_USER_PASSWORD: ${MARIADB_ROOT_USER_PASSWORD}
      MARIADB_FOLDER: ${MARIADB_FOLDER}
      MARIADB_SOCKET_FOLDER: ${MARIADB_SOCKET_FOLDER}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_USER_PASSWORD: ${WP_DB_USER_PASSWORD}
    # restart: always

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: /home/akovtune/data/mariadb
      device: /home/akovtune/inception/data/mariadb
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/akovtune/inception/data/wordpress

networks:
  inception:
    driver: bridge
