services:
    nginx:
        image: nginx
        build: ./requirements/nginx
        container_name: nginx
        ports: [ "8080:80", "8081:443" ]
        volumes:
            - ./requirements/nginx/index.html:/var/www/html/index.html:ro
        depends_on:
            - mariadb
        restart: always

    mariadb:
        image: mariadb
        build: ./requirements/mariadb
        container_name: mariadb
        environment:
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        volumes:
            - mariadb_volume:/var/lib/mysql
        restart: always

volumes:
    mariadb_volume:
