services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpress_volume:${WORDPRESS_DATA}
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DATA: ${WORDPRESS_DATA}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WP_NAME: ${WP_NAME}
      WP_HOST: ${WP_HOST}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_EMAIL: ${WP_EMAIL}
    volumes:
      - wordpress_volume:${WORDPRESS_DATA}
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATA: ${MARIADB_DATA}
      MARIADB_SOCKET_FOLDER: ${MARIADB_SOCKET_FOLDER}
    volumes:
      - mariadb_volume:${MARIADB_DATA}
    networks:
      - inception
    restart: always

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: /home/akovtune/data/mariadb
      device: /home/akovtune/inception/data/mariadb
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/akovtune/inception/data/wordpress

networks:
  inception:
    driver: bridge
